---
title: "Exploratory Data Analysis"
output: html_notebook
author: Carson Sprock
---

```{r}
library(tidyverse)
library(forecast)
library(pracma)
library(corrplot)
```

```{r}
combined_data <- read_csv("~/data/combined_data.csv") %>%
  dplyr::select(-Period) %>%
  filter(Geography != "District Of Columbia") %>%
  mutate(
    Geography=as.factor(Geography)
  )

# remove NAs (corresponding to the hold-out set)

combined_data <- combined_data %>% drop_na()

econ_vars <- c("GDP", "labor_part", "PCI")
pop_vars <- c("migration_qtr", "total_pop")
housing_vars <- c("HPI", "purch_orig", "refi_orig", "hsng_affrdblty")

make_index <- function(x){
  (x / x[1])*100
}


indices <- combined_data %>%
  group_by(Geography) %>%
  mutate_at(setdiff(colnames(combined_data), c("Period_d","Geography")), make_index) %>%
  ungroup()
```

First we look for outliers in the original time series. Pervious visual inspection showed the presense of some 

```{r}
percent_change <- function(x){
  return((x - lag(x))/lag(x))
}

flag_outliers <- function(x, thresh=1){
  possible_outliers <- abs(percent_change(x)) > thresh
  
  if (sum(possible_outliers, na.rm=TRUE) > 0){
    return(which(possible_outliers) - 1)
  } else{
    return(NULL)
  }
}


check_for_outliers <- function(data, cols_to_check){
  indices_to_check <- list()
  
  for (c in cols_to_check){
    vec <- pull(data, c)
    outliers <- flag_outliers(vec)
    if (!is.null(outliers)){
      indices_to_check[[c]] <- outliers
    }
  }
  
  return(indices_to_check)
}


cols_to_check <- setdiff(colnames(combined_data), c("Geography", "Period_d", "refi_orig"))

state_list <- list()
for (state in unique(combined_data$Geography)){
  data <- combined_data[combined_data$Geography==eval(state), ]
  state_list[[state]] <- check_for_outliers(data, cols_to_check)
}
```



```{r}
STATE <- "Alabama"

combined_data %>%
  filter(Geography==eval(STATE)) %>%
  dplyr::select(c(HPI, econ_vars)) %>%
  ts(start=c(1990,1), end=c(2018,2), frequency=4) %>%
  autoplot(facet=TRUE) + ggtitle("Economic Variables", subtitle=eval(STATE))


combined_data %>%
  filter(Geography==eval(STATE)) %>%
  dplyr::select(c(HPI, housing_vars)) %>%
  ts(start=c(1990,1), end=c(2018,2), frequency=4) %>%
  autoplot(facet=TRUE) + ggtitle("Housing Variables", subtitle=eval(STATE))

combined_data %>%
  filter(Geography==eval(STATE)) %>%
  dplyr::select(c(HPI, pop_vars)) %>%
  ts(start=c(1990,1), end=c(2018,2), frequency=4) %>%
  autoplot(facet=TRUE) + ggtitle("Population Variables", subtitle=eval(STATE))

```


```{r}

# impute mean for outliers/bad data

# none of the outliers were on the boundary of the time series or spanned more than two periods
# so we can take the mean of the series before and after
impute_mean <- function(x, i){
  return(mean(x[i-1], x[i+1]))
}

## Impute hsng_affrdblty
combined_data$hsng_affrdblty[which(combined_data$hsng_affrdblty < 10)] <- NA

for (state in unique(combined_data$Geography)){
  
  # get the indices for the each state 
  idx <- with(combined_data, which(Geography==eval(state) & is.na(hsng_affrdblty)))
  
  for (i in idx){
    combined_data$hsng_affrdblty[i] <- impute_mean(combined_data$hsng_affrdblty, i)
  }

}

## Impute migration_qtr

idx <- with(combined_data, which(Geography=="Alabama" & migration_qtr > 15))
combined_data$migration_qtr[idx] <- impute_mean(combined_data$migration_qtr, idx)

```

# Preliminary Analysis

```{r}

combined_data <- combined_data %>% group_by(Geography) %>%
  mutate(
    refi_orig_ma = pracma::movavg(refi_orig, 4, "e"),
    purch_orig_ma = pracma::movavg(purch_orig, 4, "e")
  ) %>% ungroup()



```

```{r}
STATE <- "Alabama"
combined_data %>%
  filter(Geography==eval(STATE)) %>%
  ggplot() + 
  geom_line(
    mapping=aes(
      x=Period_d,
      y=purch_orig
    )
  ) + 
  geom_line(
    mapping=aes(
      x=Period_d,
      y=purch_orig_ma
    ),
    color="red"
  )  


```


## Cross-State Comparisons

```{r}
combined_data %>%
  ggplot() + 
  geom_line(
    mapping=aes(
      x=Period_d,
      y=HPI,
      color=Geography
    )
  ) + scale_color_brewer(palette="Dark2") + xlab("Date") + 
  ggtitle("Cross-State Comparison of HPI") +  scale_x_date(date_labels="%Y", date_breaks="2 year") +
  theme(axis.text.x = element_text(angle = 45, hjust=1))


indices %>%
  ggplot() + 
  geom_line(
    mapping=aes(
      x=Period_d,
      y=GDP,
      color=Geography
    )
  ) + scale_color_brewer(palette="Dark2") + xlab("Date") + ylab("GDP (Index)") + 
  ggtitle("Cross-State Comparison of GDP", subtitle="Index, 1990Q1 = 100") +  
  scale_x_date(date_labels="%Y", date_breaks="2 year") +
  theme(axis.text.x = element_text(angle = 45, hjust=1))


combined_data %>%
  ggplot() + 
  geom_line(
    mapping=aes(
      x=Period_d,
      y=hsng_affrdblty,
      color=Geography
    )
  ) + scale_color_brewer(palette="Dark2") + xlab("Date") + 
  ggtitle("Cross-State Comparison of Housing Affordability Index") +  
  scale_x_date(date_labels="%Y", date_breaks="2 year") +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

# 
# indices %>%
#   ggplot() + 
#   geom_line(
#     mapping=aes(
#       x=Period_d,
#       y=purch_orig,
#       color=Geography
#     )
#   ) + scale_color_brewer(palette="Dark2") + xlab("Date") + 
#   ggtitle("Cross-State Comparison of Original Purchase (?)", subtitle="Index, 1990Q1 = 100") +  
#   scale_x_date(date_labels="%Y", date_breaks="2 year") +
#   theme(axis.text.x = element_text(angle = 45, hjust=1))
# 
# 
# indices %>%
#   ggplot() + 
#   geom_line(
#     mapping=aes(
#       x=Period_d,
#       y=refi_orig,
#       color=Geography
#     )
#   ) + scale_color_brewer(palette="Dark2") + xlab("Date") + 
#   ggtitle("Cross-State Comparison of Original Refinance (?)", subtitle="Index, 1990Q1 = 100") +  
#   scale_x_date(date_labels="%Y", date_breaks="2 year") +
#   theme(axis.text.x = element_text(angle = 45, hjust=1))


combined_data %>%
  ggplot(
    mapping=aes(
      x=hsng_affrdblty,
      y=HPI,
      color=Geography
    )) + 
  geom_point() + 
  geom_smooth(
    method="lm",
    se=FALSE
  ) +
  scale_color_brewer(palette="Dark2") + xlab("Housing Affordability Index") + 
  ggtitle("HPI vs Housing Affordability Index") 
```

```{r}
combined_data %>%
  dplyr::select(Period_d, Geography, purch_orig) %>%
  ggplot(mapping=aes(x=Period_d, y=purch_orig)) +
  geom_line() + 
  facet_grid(Geography ~. )
```


## Differencing the Series

```{r}


combined_data %>%
  group_by(Geograph) %>%
  

```


```{r}

# corrplot(
#   corr=X_corr,
#   method="color",
#   type="lower",
#   addCoef.col="black",
#   order="hclust",
#   number.cex=0.7,
#   tl.col="black",
#   tl.srt=45,
#   tl.offset=0.5,
#   diag=FALSE
# )


```

